---
name: Build Demo App
run-name: Building the URL Shortener
#on: [push]

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: url-shortener


jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: list env vars
        run: env
      
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10' 
      
      # - name: Install poetry
      #   uses: abatilo/actions-poetry@v2
      #   with:
      #     poetry-version: 1.2.1
      
      # - name: Testing installation
      #   run: poetry version
      
      - name: Set short sha
        id: sha
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      
      - name: Check short sha
        run: echo ${{ steps.sha.outputs.short_sha }}
      
      - id: actor
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.actor }}
      - id: step2
        run: echo ${{ steps.actor.outputs.lowercase }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DEMO_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
            
      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: "${{ env.REGISTRY }}/${{ steps.actor.outputs.lowercase }}/url-shortener:${{ steps.sha.outputs.short_sha }}"

  call_update_image_tag:
    needs: build-container
    uses: AbsolutOD/cs-gitops-demo/.github/workflows/update-image-tags.yaml@main
    with:
      image_tag: ${{needs.build_container.outputs.short_sha }}
