name: Build Demo App
run-name: Building the URL Shortener
#on: [push]

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: url-shortener

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10' 
      
      # - name: Install poetry
      #   uses: abatilo/actions-poetry@v2
      #   with:
      #     poetry-version: 1.2.1
      
      # - name: Testing installation
      #   run: poetry version
      
      - name: Set short sha
        id: sha
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      
      - name: Check short sha
        run: echo ${{ steps.sha.outputs.short_sha }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DEMO_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
            
      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: "${{ env.REGISTRY }}/${{ github.actor }}/url-shortener:${{ steps.sha.outputs.short_sha }}"
          # secrets: |
          #   GIT_AUTH_TOKEN=${{ secrets.DEMO_TOKEN }}

      # - uses: pmorelli92/github-container-registry-build-push@2.0.0
      #   name: Build and Publish latest service image
      #   with:
      #     github-push-secret: ${{secrets.DEMO_TOKEN}}
      #     docker-image-name: url-shortener
      #     docker-image-tag: ${{ steps.sha.outputs.short_sha }}
      #     #dockerfile-path: ./src/svc/Dockerfile # optional
      #     build-context: .